### PR TITLE
fix(provider): query certificate status prior using gateway

### LINKED ISSUE #1208: cli: check client cert validity before doing actions that require it
People are able to run `send-manifest` if they have a "revoked" certificate.  See [here](https://discordapp.com/channels/747885925232672829/771909909335506955/830917478027886652).

`send-manifest`, `tx deployment create`, and other commands should check not only that a certificate exists, but that it is useable.

### PR DESCRIPTION
**Pull request by troian**
fixes #1208

Signed-off-by: Artur Troian <troian.ap@gmail.com>

### CODE REVIEW

**Review by boz — COMMENTED** [review]
Do the other places that use `LoadCertificateForAccount` need to be changed too?

**Comment by troian** [comment]
fixed all

**Review by hydrogen18 — APPROVED** [review]

**Review by boz — COMMENTED** [review]
Can we get rid of the old function then?

**Review by boz — APPROVED** [review]
:rocket:

**Pull request merged**
