### PR TITLE
fix(node): reject transactions that attempt to change the groups on a deployment

### PR DESCRIPTION
**Pull request by hydrogen18**
Presently I can create a deployment

```
$ make deployment-create
/home/ericu/ovrclk/akash/.cache/bin/akash --home /home/ericu/ovrclk/akash/.cache/run/kube tx deployment create "deployment.yaml" \
	--dseq "1" \
	--from "main"
{"height":"4","txhash":"4EAEDBF812209F46338BC72632466E5601124F699382F5F8916F92F726DB062C","codespace":"","code":0,"data":"0A2F0A2D2F616B6173682E6465706C6F796D656E742E763162657461322E4D73674372656174654465706C6F796D656E74","raw_log":"[{\"events\":[{\"type\":\"akash.v1\",\"attributes\":[{\"key\":\"module\",\"value\":\"deployment\"},{\"key\":\"action\",\"value\":\"deployment-created\"},{\"key\":\"version\",\"value\":\"e782081bfdce80b3a777404073e979ca31ff8c5e4c0149bae264a258284ae5ac\"},{\"key\":\"owner\",\"value\":\"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz\"},{\"key\":\"dseq\",\"value\":\"1\"},{\"key\":\"module\",\"value\":\"market\"},{\"key\":\"action\",\"value\":\"order-created\"},{\"key\":\"owner\",\"value\":\"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz\"},{\"key\":\"dseq\",\"value\":\"1\"},{\"key\":\"gseq\",\"value\":\"1\"},{\"key\":\"oseq\",\"value\":\"1\"}]},{\"type\":\"coin_received\",\"attributes\":[{\"key\":\"receiver\",\"value\":\"akash14pphss726thpwws3yc458hggufynm9x77l4l2u\"},{\"key\":\"amount\",\"value\":\"5000000uakt\"}]},{\"type\":\"coin_spent\",\"attributes\":[{\"key\":\"spender\",\"value\":\"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz\"},{\"key\":\"amount\",\"value\":\"5000000uakt\"}]},{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"/akash.deployment.v1beta2.MsgCreateDeployment\"},{\"key\":\"sender\",\"value\":\"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"akash14pphss726thpwws3yc458hggufynm9x77l4l2u\"},{\"key\":\"sender\",\"value\":\"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz\"},{\"key\":\"amount\",\"value\":\"5000000uakt\"}]}]}]","logs":[{"msg_index":0,"log":"","events":[{"type":"akash.v1","attributes":[{"key":"module","value":"deployment"},{"key":"action","value":"deployment-created"},{"key":"version","value":"e782081bfdce80b3a777404073e979ca31ff8c5e4c0149bae264a258284ae5ac"},{"key":"owner","value":"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz"},{"key":"dseq","value":"1"},{"key":"module","value":"market"},{"key":"action","value":"order-created"},{"key":"owner","value":"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz"},{"key":"dseq","value":"1"},{"key":"gseq","value":"1"},{"key":"oseq","value":"1"}]},{"type":"coin_received","attributes":[{"key":"receiver","value":"akash14pphss726thpwws3yc458hggufynm9x77l4l2u"},{"key":"amount","value":"5000000uakt"}]},{"type":"coin_spent","attributes":[{"key":"spender","value":"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz"},{"key":"amount","value":"5000000uakt"}]},{"type":"message","attributes":[{"key":"action","value":"/akash.deployment.v1beta2.MsgCreateDeployment"},{"key":"sender","value":"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz"}]},{"type":"transfer","attributes":[{"key":"recipient","value":"akash14pphss726thpwws3yc458hggufynm9x77l4l2u"},{"key":"sender","value":"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz"},{"key":"amount","value":"5000000uakt"}]}]}],"info":"","gas_wanted":"228366","gas_used":"127968","tx":null,"timestamp":"","events":[{"type":"coin_spent","attributes":[{"key":"c3BlbmRlcg==","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=","index":true},{"key":"YW1vdW50","value":"NTcxMHVha3Q=","index":true}]},{"type":"coin_received","attributes":[{"key":"cmVjZWl2ZXI=","value":"YWthc2gxN3hwZnZha20yYW1nOTYyeWxzNmY4NHoza2VsbDhjNWxhenc4ajg=","index":true},{"key":"YW1vdW50","value":"NTcxMHVha3Q=","index":true}]},{"type":"transfer","attributes":[{"key":"cmVjaXBpZW50","value":"YWthc2gxN3hwZnZha20yYW1nOTYyeWxzNmY4NHoza2VsbDhjNWxhenc4ajg=","index":true},{"key":"c2VuZGVy","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=","index":true},{"key":"YW1vdW50","value":"NTcxMHVha3Q=","index":true}]},{"type":"message","attributes":[{"key":"c2VuZGVy","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=","index":true}]},{"type":"tx","attributes":[{"key":"ZmVl","value":"NTcxMHVha3Q=","index":true}]},{"type":"tx","attributes":[{"key":"YWNjX3NlcQ==","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcnovMA==","index":true}]},{"type":"tx","attributes":[{"key":"c2lnbmF0dXJl","value":"OWptcTFHemc1bmdDRXp5S013WnJsZVk5ZEQzV2c1Wkh0eU82RC8wcmZiaGJFU0VpLzZUOUJVTWo0dUYrNGM4WTB5NUsrSUNBVGRHM3JCbGxNSmlUd2c9PQ==","index":true}]},{"type":"message","attributes":[{"key":"YWN0aW9u","value":"L2FrYXNoLmRlcGxveW1lbnQudjFiZXRhMi5Nc2dDcmVhdGVEZXBsb3ltZW50","index":true}]},{"type":"akash.v1","attributes":[{"key":"bW9kdWxl","value":"ZGVwbG95bWVudA==","index":true},{"key":"YWN0aW9u","value":"ZGVwbG95bWVudC1jcmVhdGVk","index":true},{"key":"dmVyc2lvbg==","value":"ZTc4MjA4MWJmZGNlODBiM2E3Nzc0MDQwNzNlOTc5Y2EzMWZmOGM1ZTRjMDE0OWJhZTI2NGEyNTgyODRhZTVhYw==","index":true},{"key":"b3duZXI=","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=","index":true},{"key":"ZHNlcQ==","value":"MQ==","index":true}]},{"type":"akash.v1","attributes":[{"key":"bW9kdWxl","value":"bWFya2V0","index":true},{"key":"YWN0aW9u","value":"b3JkZXItY3JlYXRlZA==","index":true},{"key":"b3duZXI=","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=","index":true},{"key":"ZHNlcQ==","value":"MQ==","index":true},{"key":"Z3NlcQ==","value":"MQ==","index":true},{"key":"b3NlcQ==","value":"MQ==","index":true}]},{"type":"coin_spent","attributes":[{"key":"c3BlbmRlcg==","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=","index":true},{"key":"YW1vdW50","value":"NTAwMDAwMHVha3Q=","index":true}]},{"type":"coin_received","attributes":[{"key":"cmVjZWl2ZXI=","value":"YWthc2gxNHBwaHNzNzI2dGhwd3dzM3ljNDU4aGdndWZ5bm05eDc3bDRsMnU=","index":true},{"key":"YW1vdW50","value":"NTAwMDAwMHVha3Q=","index":true}]},{"type":"transfer","attributes":[{"key":"cmVjaXBpZW50","value":"YWthc2gxNHBwaHNzNzI2dGhwd3dzM3ljNDU4aGdndWZ5bm05eDc3bDRsMnU=","index":true},{"key":"c2VuZGVy","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=","index":true},{"key":"YW1vdW50","value":"NTAwMDAwMHVha3Q=","index":true}]},{"type":"message","attributes":[{"key":"c2VuZGVy","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=","index":true}]}]}

```

Then query it 

```
$ akash query deployment get --dseq 1 --owner akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz
deployment:
  created_at: "4"
  deployment_id:
    dseq: "1"
    owner: akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz
  state: active
  version: 54IIG/3OgLOnd0BAc+l5yjH/jF5MAUm64mSiWChK5aw=
escrow_account:
  balance:
    amount: "5000000.000000000000000000"
    denom: uakt
  depositor: akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz
  funds:
    amount: "0.000000000000000000"
    denom: uakt
  id:
    scope: deployment
    xid: akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz/1
  owner: akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz
  settled_at: "4"
  state: open
  transferred:
    amount: "0.000000000000000000"
    denom: uakt
groups:
- created_at: "4"
  group_id:
    dseq: "1"
    gseq: 1
    owner: akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz
  group_spec:
    name: westcoast
    requirements:
      attributes:
      - key: region
        value: us-west
      signed_by:
        all_of: []
        any_of: []
    resources:
    - count: 1
      price:
        amount: "1000.000000000000000000"
        denom: uakt
      resources:
        cpu:
          attributes: []
          units:
            val: "100"
        endpoints:
        - kind: SHARED_HTTP
          sequence_number: 0
        memory:
          attributes: []
          quantity:
            val: "16777216"
        storage:
        - attributes: []
          name: default
          quantity:
            val: "134217728"
    - count: 1
      price:
        amount: "1000.000000000000000000"
        denom: uakt
      resources:
        cpu:
          attributes: []
          units:
            val: "100"
        endpoints:
        - kind: RANDOM_PORT
          sequence_number: 0
        - kind: RANDOM_PORT
          sequence_number: 0
        memory:
          attributes: []
          quantity:
            val: "16777216"
        storage:
        - attributes: []
          name: default
          quantity:
            val: "134217728"
  state: open
```

It's active and exists as intended. Next I broadcast an update transaction that changes the groups.

```
$ make deployment-update
/home/ericu/ovrclk/akash/.cache/bin/akash --home /home/ericu/ovrclk/akash/.cache/run/kube tx deployment update "deployment.yaml" \
	--dseq "1" \
	--from "main"
{"height":"18","txhash":"3D7E24B16D9A3D63F131123E47F163B59DAEBE6171740D454C61096D0E84009F","codespace":"","code":0,"data":"0A2F0A2D2F616B6173682E6465706C6F796D656E742E763162657461322E4D73675570646174654465706C6F796D656E74","raw_log":"[{\"events\":[{\"type\":\"akash.v1\",\"attributes\":[{\"key\":\"module\",\"value\":\"deployment\"},{\"key\":\"action\",\"value\":\"deployment-updated\"},{\"key\":\"version\",\"value\":\"6084d1cb30eee3aa81b090da09fcb0f6e23371cfbeaac8fd34c14188327135cb\"},{\"key\":\"owner\",\"value\":\"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz\"},{\"key\":\"dseq\",\"value\":\"1\"}]},{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"/akash.deployment.v1beta2.MsgUpdateDeployment\"}]}]}]","logs":[{"msg_index":0,"log":"","events":[{"type":"akash.v1","attributes":[{"key":"module","value":"deployment"},{"key":"action","value":"deployment-updated"},{"key":"version","value":"6084d1cb30eee3aa81b090da09fcb0f6e23371cfbeaac8fd34c14188327135cb"},{"key":"owner","value":"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz"},{"key":"dseq","value":"1"}]},{"type":"message","attributes":[{"key":"action","value":"/akash.deployment.v1beta2.MsgUpdateDeployment"}]}]}],"info":"","gas_wanted":"106576","gas_used":"64409","tx":null,"timestamp":"","events":[{"type":"coin_spent","attributes":[{"key":"c3BlbmRlcg==","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=","index":true},{"key":"YW1vdW50","value":"MjY2NXVha3Q=","index":true}]},{"type":"coin_received","attributes":[{"key":"cmVjZWl2ZXI=","value":"YWthc2gxN3hwZnZha20yYW1nOTYyeWxzNmY4NHoza2VsbDhjNWxhenc4ajg=","index":true},{"key":"YW1vdW50","value":"MjY2NXVha3Q=","index":true}]},{"type":"transfer","attributes":[{"key":"cmVjaXBpZW50","value":"YWthc2gxN3hwZnZha20yYW1nOTYyeWxzNmY4NHoza2VsbDhjNWxhenc4ajg=","index":true},{"key":"c2VuZGVy","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=","index":true},{"key":"YW1vdW50","value":"MjY2NXVha3Q=","index":true}]},{"type":"message","attributes":[{"key":"c2VuZGVy","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=","index":true}]},{"type":"tx","attributes":[{"key":"ZmVl","value":"MjY2NXVha3Q=","index":true}]},{"type":"tx","attributes":[{"key":"YWNjX3NlcQ==","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcnovMQ==","index":true}]},{"type":"tx","attributes":[{"key":"c2lnbmF0dXJl","value":"eEUxN1ZvTzRuZi9oWlQ1azhuQ0V4dWJYenlUSFJYZVZsQkNZWUZUYThKdzZyK0xYSXpBdklDZDNNVDJSVUxrQURjWlF0M1V3eDFYYitNR3diSFpMYUE9PQ==","index":true}]},{"type":"message","attributes":[{"key":"YWN0aW9u","value":"L2FrYXNoLmRlcGxveW1lbnQudjFiZXRhMi5Nc2dVcGRhdGVEZXBsb3ltZW50","index":true}]},{"type":"akash.v1","attributes":[{"key":"bW9kdWxl","value":"ZGVwbG95bWVudA==","index":true},{"key":"YWN0aW9u","value":"ZGVwbG95bWVudC11cGRhdGVk","index":true},{"key":"dmVyc2lvbg==","value":"NjA4NGQxY2IzMGVlZTNhYTgxYjA5MGRhMDlmY2IwZjZlMjMzNzFjZmJlYWFjOGZkMzRjMTQxODgzMjcxMzVjYg==","index":true},{"key":"b3duZXI=","value":"YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=","index":true},{"key":"ZHNlcQ==","value":"MQ==","index":true}]}]}

```

This transaction is accepted by the network

```
$ akash query tx 3D7E24B16D9A3D63F131123E47F163B59DAEBE6171740D454C61096D0E84009F
code: 0
codespace: ""
data: 0A2F0A2D2F616B6173682E6465706C6F796D656E742E763162657461322E4D73675570646174654465706C6F796D656E74
events:
- attributes:
  - index: true
    key: c3BlbmRlcg==
    value: YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=
  - index: true
    key: YW1vdW50
    value: MjY2NXVha3Q=
  type: coin_spent
- attributes:
  - index: true
    key: cmVjZWl2ZXI=
    value: YWthc2gxN3hwZnZha20yYW1nOTYyeWxzNmY4NHoza2VsbDhjNWxhenc4ajg=
  - index: true
    key: YW1vdW50
    value: MjY2NXVha3Q=
  type: coin_received
- attributes:
  - index: true
    key: cmVjaXBpZW50
    value: YWthc2gxN3hwZnZha20yYW1nOTYyeWxzNmY4NHoza2VsbDhjNWxhenc4ajg=
  - index: true
    key: c2VuZGVy
    value: YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=
  - index: true
    key: YW1vdW50
    value: MjY2NXVha3Q=
  type: transfer
- attributes:
  - index: true
    key: c2VuZGVy
    value: YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=
  type: message
- attributes:
  - index: true
    key: ZmVl
    value: MjY2NXVha3Q=
  type: tx
- attributes:
  - index: true
    key: YWNjX3NlcQ==
    value: YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcnovMQ==
  type: tx
- attributes:
  - index: true
    key: c2lnbmF0dXJl
    value: eEUxN1ZvTzRuZi9oWlQ1azhuQ0V4dWJYenlUSFJYZVZsQkNZWUZUYThKdzZyK0xYSXpBdklDZDNNVDJSVUxrQURjWlF0M1V3eDFYYitNR3diSFpMYUE9PQ==
  type: tx
- attributes:
  - index: true
    key: YWN0aW9u
    value: L2FrYXNoLmRlcGxveW1lbnQudjFiZXRhMi5Nc2dVcGRhdGVEZXBsb3ltZW50
  type: message
- attributes:
  - index: true
    key: bW9kdWxl
    value: ZGVwbG95bWVudA==
  - index: true
    key: YWN0aW9u
    value: ZGVwbG95bWVudC11cGRhdGVk
  - index: true
    key: dmVyc2lvbg==
    value: NjA4NGQxY2IzMGVlZTNhYTgxYjA5MGRhMDlmY2IwZjZlMjMzNzFjZmJlYWFjOGZkMzRjMTQxODgzMjcxMzVjYg==
  - index: true
    key: b3duZXI=
    value: YWthc2gxcHZjOTVmY2UzcmQ2bWNodzR6NWEybHo3d2RnbmowNTk5bjdqcno=
  - index: true
    key: ZHNlcQ==
    value: MQ==
  type: akash.v1
gas_used: "64409"
gas_wanted: "106576"
height: "18"
info: ""
logs:
- events:
  - attributes:
    - key: module
      value: deployment
    - key: action
      value: deployment-updated
    - key: version
      value: 6084d1cb30eee3aa81b090da09fcb0f6e23371cfbeaac8fd34c14188327135cb
    - key: owner
      value: akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz
    - key: dseq
      value: "1"
    type: akash.v1
  - attributes:
    - key: action
      value: /akash.deployment.v1beta2.MsgUpdateDeployment
    type: message
  log: ""
  msg_index: 0
raw_log: '[{"events":[{"type":"akash.v1","attributes":[{"key":"module","value":"deployment"},{"key":"action","value":"deployment-updated"},{"key":"version","value":"6084d1cb30eee3aa81b090da09fcb0f6e23371cfbeaac8fd34c14188327135cb"},{"key":"owner","value":"akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz"},{"key":"dseq","value":"1"}]},{"type":"message","attributes":[{"key":"action","value":"/akash.deployment.v1beta2.MsgUpdateDeployment"}]}]}]'
timestamp: "2022-04-13T21:00:17Z"
tx:
  '@type': /cosmos.tx.v1beta1.Tx
  auth_info:
    fee:
      amount:
      - amount: "2665"
        denom: uakt
      gas_limit: "106576"
      granter: ""
      payer: ""
    signer_infos:
    - mode_info:
        single:
          mode: SIGN_MODE_DIRECT
      public_key:
        '@type': /cosmos.crypto.secp256k1.PubKey
        key: AwsCGTlyWaZgG/fXlDY5xG19jQIUVXvv9YwTkIrjmA+g
      sequence: "1"
  body:
    extension_options: []
    memo: ""
    messages:
    - '@type': /akash.deployment.v1beta2.MsgUpdateDeployment
      groups:
      - name: westcoast
        requirements:
          attributes:
          - key: region
            value: us-west
          signed_by:
            all_of: []
            any_of: []
        resources:
        - count: 1
          price:
            amount: "1000.000000000000000000"
            denom: uakt
          resources:
            cpu:
              attributes: []
              units:
                val: "100"
            endpoints:
            - kind: SHARED_HTTP
              sequence_number: 0
            memory:
              attributes: []
              quantity:
                val: "25165824"
            storage:
            - attributes: []
              name: default
              quantity:
                val: "134217728"
        - count: 1
          price:
            amount: "1000.000000000000000000"
            denom: uakt
          resources:
            cpu:
              attributes: []
              units:
                val: "100"
            endpoints:
            - kind: RANDOM_PORT
              sequence_number: 0
            - kind: RANDOM_PORT
              sequence_number: 0
            memory:
              attributes: []
              quantity:
                val: "25165824"
            storage:
            - attributes: []
              name: default
              quantity:
                val: "134217728"
      id:
        dseq: "1"
        owner: akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz
      version: YITRyzDu46qBsJDaCfyw9uIzcc++qsj9NMFBiDJxNcs=
    non_critical_extension_options: []
    timeout_height: "0"
  signatures:
  - xE17VoO4nf/hZT5k8nCExubXzyTHRXeVlBCYYFTa8Jw6r+LXIzAvICd3MT2RULkADcZQt3Uwx1Xb+MGwbHZLaA==
txhash: 3D7E24B16D9A3D63F131123E47F163B59DAEBE6171740D454C61096D0E84009F

```

If you look , I changed the memory on the group from 16 megabytes to 24.

But if I query the original deployment a second time it still shows up unchanged

```
$ akash query deployment get --dseq 1 --owner akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz
deployment:
  created_at: "4"
  deployment_id:
    dseq: "1"
    owner: akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz
  state: active
  version: YITRyzDu46qBsJDaCfyw9uIzcc++qsj9NMFBiDJxNcs=
escrow_account:
  balance:
    amount: "5000000.000000000000000000"
    denom: uakt
  depositor: akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz
  funds:
    amount: "0.000000000000000000"
    denom: uakt
  id:
    scope: deployment
    xid: akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz/1
  owner: akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz
  settled_at: "4"
  state: open
  transferred:
    amount: "0.000000000000000000"
    denom: uakt
groups:
- created_at: "4"
  group_id:
    dseq: "1"
    gseq: 1
    owner: akash1pvc95fce3rd6mchw4z5a2lz7wdgnj0599n7jrz
  group_spec:
    name: westcoast
    requirements:
      attributes:
      - key: region
        value: us-west
      signed_by:
        all_of: []
        any_of: []
    resources:
    - count: 1
      price:
        amount: "1000.000000000000000000"
        denom: uakt
      resources:
        cpu:
          attributes: []
          units:
            val: "100"
        endpoints:
        - kind: SHARED_HTTP
          sequence_number: 0
        memory:
          attributes: []
          quantity:
            val: "16777216"
        storage:
        - attributes: []
          name: default
          quantity:
            val: "134217728"
    - count: 1
      price:
        amount: "1000.000000000000000000"
        denom: uakt
      resources:
        cpu:
          attributes: []
          units:
            val: "100"
        endpoints:
        - kind: RANDOM_PORT
          sequence_number: 0
        - kind: RANDOM_PORT
          sequence_number: 0
        memory:
          attributes: []
          quantity:
            val: "16777216"
        storage:
        - attributes: []
          name: default
          quantity:
            val: "134217728"
  state: open
```

So this is a bug in that you can broadcast a transaction that appears to change the deployment groups, but in fact does not. We should just reject the transaction at that point if the groups have changed.

Also, reject the transaction if it doesn't change the version. It's a no-op which is pointless to accept if there is no data being updated on change.

### CODE REVIEW

**Comment by hydrogen18** [comment]
Apparently this breaks some tests, because they expect to run no-op deployment update transactions. I have no idea why we test this. I'll wait until I hear feedback on the PR until I bother refactoring those tests.

**Review by boz — COMMENTED** [review]
I think that the only thing that can be updated here is the `Version` field.  I believe the previous approach was:

* Send minimal data - `DeploymentID` and `Version`
* Validate groups client-side.

Not having `Groups` in [`UpdateDeploymentMsg`](https://github.com/ovrclk/akash/blob/14a9ba4e59d03963dc5c409b18f2a2d555904ef1/proto/akash/deployment/v1beta2/deploymentmsg.proto#L75-L93) makes it explicit.  I think including `Groups` was an (easy) oversight.

**Comment by hydrogen18** [comment]
Should we change the grpc just to not have the `groups`  field?

**Comment by boz** [comment]
yes, I think so

**Comment by boz** [comment]
the provider should be checking that the total resources don't change in send-manifest too.  not sure if that got lost too.  the same check can be used in the cli. 

it used to allow for moving resources from one service to another, but i don't know if this is a good thing and i don't really care too much if we still support this.

**Comment by hydrogen18** [comment]
@boz  I incorporated your feedback. The `groups` field is gone in the update message now. The update command won't send the transaction if a user tries to change their groups, since it isn't possible.

The provider is checking for a version match (between the on-chain value & what is sent) on update, so it shouldn't have any issues there.

**Review by boz — APPROVED** [review]

**Pull request merged**
