### PR TITLE
Update Cosmos-SDK dep to v0.38.0 

### PR DESCRIPTION
**Pull request by jackzampolin**
---
name: Jack Zampolin
about: Foo, Bar, AND Baz
title: ''Update CosmosSDK dependancies to v0.38.0"
labels: ''cosmos-sdk dependancies"
assignees: '@boz @gosuri'

---

## Description

This updates `akash` to v0.38.0 of the `cosmos-sdk`. One note: there is an issue with this release (https://github.com/cosmos/cosmos-sdk/pull/5579) that will be fixed in a forthcoming `v0.38.1`. I think waiting until that code is ready might be the right way to move forward here.

### CODE REVIEW

**Comment by jackzampolin** [comment]
Build failing with following error I'm unable to recreate locally: 

```
GO111MODULE=on go build ./...
# github.com/ChainSafe/go-schnorrkel
../../../../pkg/mod/github.com/!chain!safe/go-schnorrkel@v0.0.0-20200102211924-4bcbc698314f/helpers.go:22:18: syntax error: unexpected b00000111 at end of statement
note: module requires Go 1.13Makefile:23: recipe for target 'build' failed
make: *** [build] Error 2
The command "make" exited with 2.

```

**Comment by gosuri** [comment]
i cant replicate the build error on my mac too, taking a look at travis

**Comment by gosuri** [comment]
hey @jackzampolin, are you seeing this error on your mac?

**Comment by jackzampolin** [comment]
@gosuri RE: noisy logging, its an issue for users who have updated to the latest MacOS. I've got a PR up to silence it.

**Pull request merged**
