### PR TITLE
feat(goreleaser): edgenet homebrew tap

### LINKED ISSUE #888: split homebrew release in to multiple taps
Homebrew does not support multiple versions of single formulae thus it installs whatever is in recipe (though it still can install recipe and HEAD version from git).
For example when mainnet released with version `v0.2.0` followed by release on master `v0.3.0` actual formulae will contain release `v0.3.0` which might be incompatible (i.e. network reset etc) with mainnet.

One of options to avoid this is to not allow edge releases to deploy to mainnet homebrew formulae.
Edge releases though still may need to be accessed from homebrew for testing purposes. That can be achieved with creating keg-only formulae named something like `akash-edge`.
This approach imposes maintaining of two separate goreleaser configs.

### PR DESCRIPTION
**Pull request by boz**
fixes #888

### CODE REVIEW

**Review by troian — APPROVED** [review]

**Comment by troian** [comment]
just came with idea we might be able to leave with one `.goreleaser.yaml`

**Comment by troian** [comment]
@boz https://github.com/ovrclk/akash/commit/b05ce9edba9a852295f11cc63a09b0f950f33fa9

**Comment by troian** [comment]
@boz force-pushed change of edge tap name to `akash-edge`
https://github.com/ovrclk/akash/pull/900/commits/a5b2b498f2bbb4166b5b590c074ff4bacf7f14ca

**Comment by boz** [comment]
superseded by #900

**Pull request closed without merging**
