### PR TITLE
Mainnet prep : Cleanup the upgrade handler

### PR DESCRIPTION
**Pull request by anilCSE**
---
name: Pull Request
about: Submit a pull request
title: ''
labels: ''
assignees: '@boz @gosuri'

---

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/ovrclk/akash/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/ovrclk/akash/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jackzampolin** [comment]
I think in this PR we would also want to disable the akash specific modules an just run with the base setup. Maybe this should be in another PR (I'm giving my approval here) or on a release branch or something.

**Comment by boz** [comment]
@jackzampolin isn't this for the testnet release, which would need our modules?

**Comment by anilCSE** [comment]
> I think in this PR we would also want to disable the akash specific modules an just run with the base setup. Maybe this should be in another PR (I'm giving my approval here) or on a release branch or something.

If we disable akash specific modules, we would also need to comment out all the test scripts associated. If we are going to comment out all the tests, it's better to cut the release from a release branch.

**Comment by boz** [comment]
We'll be doing this in the `mainnet` branch.  I made a PR for it that includes not running integration.

**Pull request merged**
