### PR TITLE
Update Cosmos SDK to v0.40.0-rc3

### PR DESCRIPTION
**Pull request by jackzampolin**
This PR is now ready for review. It updates the SDK version to the latest RC. This RC should be substantially the release version as the SDK and tendermint teams have everything in for 0.40.0. Only the IBC team has remaining issues. We anticipate a v0.40.0-rc3 late next week containing the last items that will be 0.40.0 final.

### CODE REVIEW

**Comment by hydrogen18** [comment]
@jackzampolin What's the goal of this? It looks like it moving us from v0.40 to v0.34

**Comment by jackzampolin** [comment]
@hydrogen18 there are some changes between the current `rc0` commit and the upcoming `rc2`. This PR updates the code to incorporate those changes. I'm using this to test the relayer. Will move PR out of WIP when there is new RC from the SDK team.

**Comment by jackzampolin** [comment]
Ok @anilCSE and @akhilkumarpilli I've done some work to try to impl `ADR31` (I think) and I'm getting the following error when trying to run `akash start` with a properly configured node:

```
I[2020-10-28|16:53:42.223] starting ABCI with Tendermint                module=main 
panic: type_url /cosmos.vesting.v1beta1.Msg/CreateVestingAccount has not been registered yet. Before calling RegisterService, you must register all interfaces by calling the `RegisterInterfaces` method on module.BasicManager. Each module should call `msgservice.RegisterMsgServiceDesc` inside its `RegisterInterfaces` method with the `_Msg_serviceDesc` generated by proto-gen

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService(0xc0001589e0, 0x79563e0, 0x629cf20, 0xc000d18960)
	github.com/cosmos/cosmos-sdk@v0.34.4-0.20201028192045-82f15f306e8a/baseapp/msg_service_router.go:58 +0x33a
github.com/cosmos/cosmos-sdk/x/auth/vesting/types.RegisterMsgServer(...)
	github.com/cosmos/cosmos-sdk@v0.34.4-0.20201028192045-82f15f306e8a/x/auth/vesting/types/tx.pb.go:277
github.com/cosmos/cosmos-sdk/x/auth/vesting.AppModule.RegisterServices(0x682fd60, 0xc0002688a0, 0x6891d00, 0xc000e56ed0, 0x6891d00, 0xc000e56ed0, 0xc0011c0500, 0x682fd60, 0xc000268910, 0x682fde0, ...)
	github.com/cosmos/cosmos-sdk@v0.34.4-0.20201028192045-82f15f306e8a/x/auth/vesting/module.go:105 +0x145
github.com/cosmos/cosmos-sdk/types/module.(*Manager).RegisterServices(0xc00102ce00, 0x6837e20, 0xc000158fe0)
	github.com/cosmos/cosmos-sdk@v0.34.4-0.20201028192045-82f15f306e8a/types/module/module.go:293 +0xa7
github.com/ovrclk/akash/app.NewApp(0x68750a0, 0xc000e58680, 0x689b0c0, 0xc000612200, 0x0, 0x0, 0x0, 0xc000e825a0, 0x7ffeefbffa35, 0xb, ...)
	github.com/ovrclk/akash/app/app.go:359 +0x55e5
github.com/ovrclk/akash/cmd/akash/cmd.newApp(0x68750a0, 0xc000e58680, 0x689b0c0, 0xc000612200, 0x0, 0x0, 0x680fbe0, 0xc000259c20, 0xb0af59b300000000, 0xc001066f00)
	github.com/ovrclk/akash/cmd/akash/cmd/root.go:140 +0x93d
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc001059a80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6874c20, 0xc000240030, ...)
	github.com/cosmos/cosmos-sdk@v0.34.4-0.20201028192045-82f15f306e8a/server/start.go:208 +0x18d
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000d12b00, 0xc0000b6880, 0x0, 0x4, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.34.4-0.20201028192045-82f15f306e8a/server/start.go:117 +0x154
github.com/spf13/cobra.(*Command).execute(0xc000d12b00, 0xc0000b6840, 0x4, 0x4, 0xc000d12b00, 0xc0000b6840)
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00057d8c0, 0x630775a, 0x5, 0xc001122800)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.1.1/command.go:888
github.com/ovrclk/akash/cmd/akash/cmd.Execute(0xc00057d8c0, 0x6888ee0, 0xc00112eec0)
	github.com/ovrclk/akash/cmd/akash/cmd/root.go:87 +0x165
main.main()
	github.com/ovrclk/akash/cmd/akash/main.go:12 +0x2a
```

**Comment by akhilkumarpilli** [comment]
@jackzampolin , fixed above issue. Please cross check once.

**Comment by jackzampolin** [comment]
Thank you @akhilkumarpilli! Working again.

**Comment by boz** [comment]
@akhilkumarpilli can you update this to `v0.40.0-rc4`?  I believe that version includes a fix from @hydrogen18 related to viper configuration that we can't do without.

**Comment by akhilkumarpilli** [comment]
> @akhilkumarpilli can you update this to `v0.40.0-rc4`? I believe that version includes a fix from @hydrogen18 related to viper configuration that we can't do without.

@boz , `v0.40.0-rc4` is not yet released. I think we need to wait for release.

**Comment by boz** [comment]
Thanks @akhilkumarpilli .   @hydrogen18 is your change in `0.40.0-rc3`?

**Pull request merged**
