### PR TITLE
Create Dockerfile.instant

### PR DESCRIPTION
**Pull request by faddat**
This runs akash without the need to interact with it.

---
name: Pull Request
about: Submit a pull request
title: ''
labels: ''
assignees: '@boz @gosuri'

---

## Description
Adds an "instant" dockerfile that gets a node going without any configuration.  

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/ovrclk/akash/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/ovrclk/akash/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by faddat** [comment]
Yes, it's to start a node with no user intervention 

```bash
docker run -d faddat/instakash
```

I did not move the data directory correctly in CMD, fixing that now.

**Comment by boz** [comment]
We have [akash-on-akash](//github.com/ovrclk/akash-on-akash) for this @faddat

**Comment by faddat** [comment]
@boz pretty sure that AoA would fail, because it doesn't use the snapshot for sync.

**Comment by faddat** [comment]
Should I maybe make a PR against AoA?

**Pull request closed without merging**
