### PR TITLE
Add proto formatting tool

### PR DESCRIPTION
**Pull request by akhilkumarpilli**
**Changes**:
* Add `clang-format` for proto formatting

Merge #803 before merging this PR

### CODE REVIEW

**Review by anilCSE — COMMENTED** [review]
lgtm. ~~Can you move all other changes (which are not relavant to `clang-format`) to a separate PR?~~

Edit: I just checked that it is based off of #803.

**Comment by troian** [comment]
should we merge this pr first then rebase https://github.com/ovrclk/akash/pull/803 and apply formatting?

**Comment by akhilkumarpilli** [comment]
> should we merge this pr first then rebase #803 and apply formatting?

As this PR is based off of #803 , this PR includes all changes made in #803 . So, I think we need to close this and raise a new PR with only clang-format installation fixes without formatting files. Will it be okay?

**Comment by troian** [comment]
should we

**Pull request closed without merging**
