### PR TITLE
Update bond denom as akt

### PR DESCRIPTION
**Pull request by anilCSE**
Fixes: #448
---
name: Pull Request
about: Submit a pull request
title: ''
labels: ''
assignees: '@boz @gosuri'

---

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/ovrclk/akash/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/ovrclk/akash/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by anilCSE** [comment]
Looks like it is easy to modify in genesis file directly than something from code. There's no direct way to update `mint` token denom from code afaik. This should be raised as an issue agaist  `cosmos-sdk`. 

/cc @jackzampolin @adamlondon

**Comment by boz** [comment]
This looks like it will work, but it is ultimately not the best route to take, I think.  In general, try not to use `init()` for overwriting variables in other packages - it leads to conflicts and difficult-to-track bugs (what if two packages do this?  what if this package isn't included? etc...).

There should be another way to configure this - either when bootstrapping the chain or via the cosmos-sdk parameters mechanism.

**Comment by anilCSE** [comment]
> This looks like it will work, but it is ultimately not the best route to take, I think. In general, try not to use `init()` for overwriting variables in other packages - it leads to conflicts and difficult-to-track bugs (what if two packages do this? what if this package isn't included? etc...).
> 
> There should be another way to configure this - either when bootstrapping the chain or via the cosmos-sdk parameters mechanism.

I also feel that, this should go here. I didn't find a better way to handle this easily than editing these params in genesis directly.

**Comment by anilCSE** [comment]
So, let's move this to ice-box for now. We'll revisit this when we find a better solution. For now, lets change the params in `genesis.json` directly

**Pull request closed without merging**
