### PR TITLE
Base Proto PR with sdk proto files

### PR DESCRIPTION
**Pull request by akhilkumarpilli**

### CODE REVIEW

**Comment by anilCSE** [comment]
@akhilkumarpilli let's fix simapp tests before merging this. wdyt?

**Comment by anilCSE** [comment]
> @akhilkumarpilli let's fix simapp tests before merging this. wdyt?

Oh, there are a lot of dependencies to make this work. May be we can fix these simapp tests onto master

**Comment by anilCSE** [comment]
@boz I suggest to merge this PR with tests failing, otherwise we would need to address a lot stuff in single PR itself. WDYT? P.S: This is not onto `master`

**Comment by boz** [comment]
@anilCSE agreed.  definitely go for it.

**Pull request merged**
