### PR TITLE
fix: install protoc-gen-cosmos into cache dir

### LINKED ISSUE #891: Generating code from protocol buffers definitions requires the executable "protoc-gen-gocosmos"
I ran `make proto-gen` and got this 

```
$ make proto-gen
GO111MODULE=on go mod tidy
go mod vendor
vendoring non-go files...
/home/ericu/akash/akash/.cache/bin/modvendor -copy="**/*.proto" -include=\
github.com/cosmos/cosmos-sdk/proto,\
github.com/cosmos/cosmos-sdk/third_party/proto
/home/ericu/akash/akash/.cache/bin/modvendor -copy="**/*.h **/*.c" -include=\
github.com/zondax/hid
/home/ericu/akash/akash/.cache/bin/modvendor -copy="**/swagger.yaml" -include=\
github.com/cosmos/cosmos-sdk/client/docs
docker run --rm -v /home/ericu/akash/akash:/workspace -w /workspace tendermintdev/docker-build-proto find ./ ! -path "./vendor/*" -name *.proto -exec clang-format -i {} \;
./script/protocgen.sh
protoc-gen-gocosmos: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--gocosmos_out: protoc-gen-gocosmos: Plugin failed with status code 1.
make/codegen.mk:24: recipe for target 'proto-gen' failed
make: *** [proto-gen] Error 1

```

It looks like we are dependent on this executable that @troian  found 

https://github.com/regen-network/cosmos-proto/tree/master/protoc-gen-gocosmos

I'm not entirely sure what role this program plays. We need to at a minimum make acquiring this executable part of the Makefile target

### PR DESCRIPTION
**Pull request by troian**
fixes #891

### CODE REVIEW

**Comment by troian** [comment]
@hydrogen18 fyi

**Comment by Ropes** [comment]
@troian should we add this package to `tools.go` so that the dependency is manged by `go mod`?

**Comment by hydrogen18** [comment]
@troian  working for me now

**Review by hydrogen18 — APPROVED** [review]

**Review by Ropes — APPROVED** [review]
Please check in `go.sum` and :rocket:

**Review by boz — COMMENTED** [review]
:+1: agree with @Ropes  - add to `tools.go`.

**Comment by troian** [comment]
it's already in [tools.go](https://github.com/ovrclk/akash/blob/8f77a64d14e2d6ba7fd773fd291f37240918d986/tools.go#L9)

**Review by boz — APPROVED** [review]
sorry meant go.mod.  i'm guessing it's already committed?

:rocket: :ship:

**Comment by troian** [comment]
yah, it is already present in [go.mod](https://github.com/ovrclk/akash/blob/8f77a64d14e2d6ba7fd773fd291f37240918d986/go.mod#L26)

**Pull request merged**
