### PR TITLE
chore: Upgrade to IBC 2.0

### LINKED ISSUE #1485: upgrade ibc to version 2.0
We should update to IBC 2.0 for the next release.

See https://github.com/Gravity-Bridge/Gravity-Bridge/pull/6

### LINKED ISSUE #1486: upgrade cosmos-sdk to v0.44.5
See https://github.com/cosmos/cosmos-sdk/releases/tag/v0.44.5

### PR DESCRIPTION
**Pull request by arijitAD**
Fixes #1485.
Fixes #1486.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/ovrclk/akash/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/ovrclk/akash/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by boz — COMMENTED** [review]
Looks good!

We should upgrade to the latest patch, tho: [`v2.0.2`](https://github.com/cosmos/ibc-go/blob/main/CHANGELOG.md#v202---2021-12-15).  I think that it requires upgrading cosmos-sdk as well (#1486)

**Comment by boz** [comment]
Thanks @arijitAD - I don't see the tag on https://github.com/ovrclk/cosmos-sdk - am I just missing it?

**Comment by arijitAD** [comment]
> Thanks @arijitAD - I don't see the tag on https://github.com/ovrclk/cosmos-sdk - am I just missing it?

Added tag: `v0.44.5-akash-1`.

**Review by boz — APPROVED** [review]
:rocket:

**Pull request merged**
