### PR TITLE
test: Add test for cosmos-sdk context flags

### PR DESCRIPTION
**Pull request by arijitAD**
This PR fixes the broken `--home` flag after cosmos v0.43.0 upgrade.
It also adds a test that passes for `--home` flag at commit: 7965cb60d97abd26067872f2369575d0ad3ac6e4 but fails at: a7163d0db50daae3f608b318da3c8740626fc9a2.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/ovrclk/akash/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/ovrclk/akash/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by troian — CHANGES_REQUESTED** [review]
I think we should use `testutil/cli/ExecTestCLICmd` and pass custom test command there with custom `RunE` handler to gonna check all flags.

**Review by dmikey — APPROVED** [review]

**Comment by arijitAD** [comment]
> I think we should use `testutil/cli/ExecTestCLICmd` and pass custom test command there with custom `RunE` handler to gonna check all flags.

Done.

The reason the `--home` flag broke is because [these lines](https://github.com/cosmos/cosmos-sdk/blob/v0.41.4/client/cmd.go#L97-L100) are missing in the [latest cosmos release](https://github.com/cosmos/cosmos-sdk/blob/v0.43.0/client/cmd.go#L90). The `--home` flag is being parsed from viper's flags in `ReadPersistentCommandFlags()`, which is then set in the context, and then the `RunE()` function of cosmos commands gets the home flag from the context and not from the viper's config. If it were being parsed from viper's config at every place, it wouldn't have broke.

**Comment by troian** [comment]
lets add these lines into our fork of cosmos-sdk and do mod replace

**Comment by arijitAD** [comment]
> lets add these lines into our fork of cosmos-sdk and do mod replace

Done

**Review by troian — APPROVED** [review]

**Review by troian — CHANGES_REQUESTED** [review]
some linters wants fixes
https://github.com/ovrclk/akash/pull/1359/checks?check_run_id=3486648255

**Review by hydrogen18 — APPROVED** [review]

**Comment by arijitAD** [comment]
> some linters want fixes
> https://github.com/ovrclk/akash/pull/1359/checks?check_run_id=3486648255

Done

**Review by troian — APPROVED** [review]

**Pull request merged**
